In [ ]:
                                                                         PROGRAM-1

In [ ]:
 write a python code to demonstrate commands for numpy and pandas

In [ ]:
CODE:

In [ ]:
import numpy as np


In [ ]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
type(a[0])

numpy.float64

In [ ]:
z=np.zeros(10)


In [ ]:
z


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
z=np.zeros(4)
z.shape=(2,2)
z

array([[0., 0.],
       [0., 0.]])

In [ ]:
z=np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
z=np.identity(2)
z

array([[1., 0.],
       [0., 1.]])

In [ ]:
z=np.array([10,20])
z

array([10, 20])

In [ ]:
z=np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [ ]:
z=np.linspace(1,2,5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
z[0:2]
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
z=np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [ ]:
z[0,0]

1

In [ ]:
z[0,:]

array([1, 2])

In [ ]:
z=np.array([[1,2,3],[3,4,5],[5,6,7]])
z

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [ ]:
z[0,:]

array([1, 2, 3])

In [ ]:
z[:,1]

array([2, 4, 6])

In [ ]:
z=np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
indices=np.array((0,2,3))
z[indices]

array([2. , 3. , 3.5])

In [ ]:
d=np.array([0,1,1,0,0],dtype=bool)
d

array([False,  True,  True, False, False])

In [ ]:
a=np.array((11,12,13,14,15,16,17,18,19,10))
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 10])

In [ ]:
a.sort()
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a.sum()

145

In [ ]:
a.mean()

14.5

In [ ]:
a.max()

19

In [ ]:
a.argmax()

9

In [ ]:
a.min()

10

In [ ]:
a.argmin()

0

In [ ]:
a.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145])

In [ ]:
a.cumprod()

array([          10,          110,         1320,        17160,
             240240,      3603600,     57657600,    980179200,
        17643225600, 335221286400])

In [ ]:
a.var()

8.25

In [ ]:
a.std()

2.8722813232690143

In [ ]:
z=np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
z.searchsorted(2.6)

2

In [ ]:
a=np.array((4,3,2,1))
a

array([4, 3, 2, 1])

In [ ]:
np.sum(a)

10

In [ ]:
np.mean(a)

2.5

In [ ]:
np.max(a)

4

In [ ]:
np.sort(a)

array([1, 2, 3, 4])

In [ ]:
np.min(a)

1

In [ ]:
np.var(a)

1.25

In [ ]:
np.std(a)

1.118033988749895

In [ ]:
np.cumsum(a)

array([ 4,  7,  9, 10])

In [ ]:
np.cumprod(a)

array([ 4, 12, 24, 24])

In [ ]:
a=np.array([12,13,14])
b=np.array([15,16,17])
a+b

array([27, 29, 31])

In [ ]:
a*b

array([180, 208, 238])

In [ ]:
a+15


array([27, 28, 29])

In [ ]:
b+10

array([25, 26, 27])

In [ ]:
a*10

array([120, 130, 140])

In [ ]:
c=np.ones((3,3))
d=np.ones((3,3))
c+d

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
c+10

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [ ]:
c*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
c@d

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [ ]:
c.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
z=np.array([2,3])
y=np.array([2,5])
z==y

array([ True, False])

In [ ]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np

In [ ]:
ser_1 = Series ([1,1,2,-3,-5,8,13])
ser_1

0     1
1     1
2     2
3    -3
4    -5
5     8
6    13
dtype: int64

In [ ]:
ser_2 = Series([1,1,2,-3,-5],index=['a','b','c','d','e'])
ser_2

a    1
b    1
c    2
d   -3
e   -5
dtype: int64

In [ ]:
ser_2[1] == ser_2['b']

<ipython-input-67-6cc25c2b26d2>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser_2[1] == ser_2['b']


True

In [ ]:
ser_2[ser_2>0]

a    1
b    1
c    2
dtype: int64

In [ ]:

ser_2*2


a     2
b     2
c     4
d    -6
e   -10
dtype: int64

In [ ]:
import numpy as np
np.exp(ser_2)

a    2.718282
b    2.718282
c    7.389056
d    0.049787
e    0.006738
dtype: float64

In [ ]:
dict_1={'foo':100,'bar':200,'baz':300}
ser_3=Series(dict_1)
ser_3

foo    100
bar    200
baz    300
dtype: int64

In [ ]:
index=['foo','bar','baz','qux']
ser_4=Series(dict_1,index=index)
ser_4

foo    100.0
bar    200.0
baz    300.0
qux      NaN
dtype: float64

In [ ]:
pd.isnull(ser_4)

foo    False
bar    False
baz    False
qux     True
dtype: bool

In [ ]:
ser_3+ser_4

bar    400.0
baz    600.0
foo    200.0
qux      NaN
dtype: float64

In [ ]:
ser_4.name='foobarqux'

In [ ]:
ser_4.index.name='label'

In [ ]:
ser_4

label
foo    100.0
bar    200.0
baz    300.0
qux      NaN
Name: foobarqux, dtype: float64

In [ ]:
ser_1.loc[0:2]

0    1
1    1
2    2
dtype: int64

In [ ]:
ser_2.iloc[1]

1

In [ ]:
data_1={'state':['VA','VA','VA','MD','MD'],
        'year':[2012,2013,2014,2014,2015],
        'pop':[5.0,5.1,5.2,4.0,4.1]}
df_1=DataFrame(data_1)
df_1

state  year  pop
0    VA  2012  5.0
1    VA  2013  5.1
2    VA  2014  5.2
3    MD  2014  4.0
4    MD  2015  4.1

In [ ]:
df_1.state

0    VA
1    VA
2    VA
3    MD
4    MD
Name: state, dtype: object

In [ ]:
                                                                                     PROGRAM-2

In [ ]:
 Write a python program to calculate mean square and mean absolute error.

In [ ]:
CODE:


In [ ]:
import numpy as np
overs = np.array([3, 6, 9, 12, 15, 18, 20])
actual_runs = np.array([15, 28, 63, 90, 120, 152, 190])
weights = [2]

def calculate_mae_mse(overs, actual_runs, w):
    predicted_runs = w * overs
    mae = np.mean(np.abs(actual_runs - predicted_runs))
    mse = np.mean((actual_runs - predicted_runs) ** 2)
    return mae, mse

for w in weights:
    mae, mse = calculate_mae_mse(overs, actual_runs, w)
    print(f"For w = {w}: MAE = {mae}, MSE = {mse}")

For w = 2: MAE = 70.28571428571429, MSE = 7253.428571428572
